---
### run all ansible scripts on new VMs to ensure baseline software is installed
# vars prompt goes here
- name: Prompt for VM_name or grouping in /etc/ansible/hosts
  vars_prompt:
  - name: VM_name
    prompt: "Enter full qualified Virtual machine name or Ansible host group to apply baseline configs"
    private: no
    default: testvmXX.bustraan.lab

  vars:
    path: /usr/lib/systemd/system/dnf-makecache.timer
    path2: /etc/dnf/automatic.conf
    VM: localhost

  hosts: "{{ VM_name }}"
  gather_facts: true
  become: true
  tasks:

# includes go here
  - name: Ensure dnf makecache service runs 1x daily
    include_tasks: dnf-makecache-service.yml
    ignore_errors: true

  - name: Ensure dnf updates are automatically applied
    include_tasks: dnf-automatic.yml

  - name: Ensure motd banner is reset
    include_tasks: reset_motd_banner.yml

  - name: Ensure shell history logging with date and time stamp is enabled
    include_tasks: shell_history_logging.yml

  - name: Ensure firewalld has removed unnecessary services
    include_tasks: firewall_cleanup.yml

  - name: Ensure sshd_config has secure and standard settings
    include_tasks: sshd_config.yml

  - name: Ensure Zabbix agent is installed
    include_tasks: zabbix-agent-new.yml

  handlers:
  - name: restart sshd
    service: name=sshd state=restarted

  - name: restart rsyslog
    service: name=rsyslog state=restarted

  - name: restart zabbix-agent
    service: name=zabbix-agent state=restarted

  - name: Restart dnf-automatic
    service: name=dnf-automatic.timer state=restarted
 
  - name: restart firewalld
    service: name=firewalld state=restarted
 
